In [128]:
import pandas as pd
import numpy as np
import re

In [129]:
#numero de columnas y rows del DF
gsai = pd.read_csv("INPUT/GSAF5.csv",encoding="latin1")
gsai.shape

(5992, 24)

In [131]:
gsai.head(20)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN
5,2016.09.15.R,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Bunbury,Fishing,Occupant: Ben Stratton,NaN,...,NaN,"West Australian, 9/15/2016",2016.09.15.R-boat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.15.R,2016.09.15.R,5988,NaN,NaN
6,2016.09.11,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,male,M,...,3' to 4' shark,"News4Jax, 9/11/2016",2016.09.11-PonteVedra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.11,2016.09.11,5987,NaN,NaN
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",Swimming,female,F,...,"Tiger shark, 10?","Hawaii News Now, 9/7/2016",2016.09.07-Oahu.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.07,2016.09.07,5986,NaN,NaN
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,Kite surfing,David Jewell,M,...,NaN,"TVANouvelles, 9/6/2016",2016.09.06-Jewell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.06,2016.09.06,5985,NaN,NaN
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,Rylie Williams,F,...,NaN,"C. Creswell, GSAF",2016.09.05.b-Williams.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.05.b,2016.09.05.b,5984,NaN,NaN
10,2016.09.05.a,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,Surfing,Fraser Penman,M,...,NaN,"Perth Now, 9/5/2016",2016.09.05.a-Penman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.05.a,2016.09.05.a,5983,NaN,NaN
11,2016.09.04,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Body boarding,Austin Moore,M,...,NaN,"Orlando Sentinel, 9/7/2016",2016.09.04-Moore.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.04,2016.09.04,5982,NaN,NaN
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",Spearfishing,Tyler McQuillen,M,...,White shark,"R. Collier, GSAF",2016.09.01-McQuillen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.01,2016.09.01,5981,NaN,NaN
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Sam Cumiskey,M,...,"Bull shark, 6'","News Channel 8, 8/30/16",2016.08.29.b-Cumiskey.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.29.b,2016.08.29.b,5980,NaN,NaN
14,2016.08.29.a,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"News Channel 8, 8/30/16",2016.08.29.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.29.a,2016.08.29.a,5979,NaN,NaN
15,2016.08.27,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,Surfing,Laurent Chardard,M,...,"Bull shark, 3.5 m","LaDepeche, 8/29/2016",2016.08.27-Chardard.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.27,2016.08.27,5978,NaN,NaN
16,2016.08.25,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,David Cassetty,M,...,NaN,"First Coast News, 7/25/2016",2016.08.25-Cassetty.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.25,2016.08.25,5977,NaN,NaN
17,2016.08.07,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,Snorkeling,Johnny Stoch,M,...,NaN,"ABC, 8/11/2016",2016.08.07-Stoch.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.07,2016.08.07,5976,NaN,NaN
18,2016.08.06,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,SUP Foil boarding,Connor Baxter,M,...,"Tiger shark, 10'","SUP, 8/9/2015",2016.08.06-Baxter.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.06,2016.08.06,5975,NaN,NaN
19,2016.08.04,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Nolan Tyler,M,...,Blacktip shark,"News 965, 8/5/2016",2016.06.04-Tyler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.04,2016.08.04,5974,NaN,NaN

In [132]:
#types de cada columna 
gsai.dtypes

Case Number               object
Date                      object
Year                       int64
Type                      object
Country                   object
Area                      object
Location                  object
Activity                  object
Name                      object
Sex                       object
Age                       object
Injury                    object
Fatal (Y/N)               object
Time                      object
Species                   object
Investigator or Source    object
pdf                       object
href formula              object
href                      object
Case Number.1             object
Case Number.2             object
original order             int64
Unnamed: 22               object
Unnamed: 23               object
dtype: object

In [133]:
#nombres de todas las columas
gsai.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [134]:
#borrar las dos ultimas columnas cuyos datos no me interesan 
to_drop=['Unnamed: 22','Unnamed: 23']
gsai1 = gsai.drop(to_drop, axis=1)
gsai1.columns
#a partir de ahora trabajaremos sobre gsai1

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order'],
      dtype='object')

In [201]:
#ordenamos por 'Country'
gsai1= gsai1.sort_values('original order')

In [202]:
#Hacemos un nuevo DF (gsai2) solo con las columnas que pueden interesarnos para la hipotesis
gsai2 = gsai1[['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Name', 'Sex ', 'Injury', 'Fatal (Y/N)', 'original order']]
#Y unificamos los nombres de las columnas
gsai2 = gsai2.rename(columns={'Sex ':'Sex', 'Fatal (Y/N)':'Fatal','original order':'Original Order' })
gsai2.head()

,Case Number,Date,Year,Type,Country,Area,Name,Sex,Injury,Fatal,Original Order
5991,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,male,M,"FATAL. ""Shark bit him in half, carrying away t...",Y,2
5990,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,Jules Patterson,M,FATAL,Y,3
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Coast Guard personnel,M,FATAL,Y,4
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Ahmun,M,FATAL,Y,5
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,male,M,FATAL,Y,6

##COLUMNA FATAL##

In [203]:
gsai2['Fatal'].isnull().sum()

19

In [204]:
gsai2['Fatal'] = gsai2['Fatal'].fillna('UNKNOWN')

In [205]:
#Miramos los diferentes valores que tiene la columna original 'Fatal (Y/N)'
#Queremos acotar todos los valores a 'N', 'Y' o 'UNKNOWN'
gsai1['Fatal (Y/N)'].value_counts()

N          4315
Y          1552
UNKNOWN      94
 N            8
N             1
F             1
n             1
#VALUE!       1
Name: Fatal (Y/N), dtype: int64

In [206]:
#reemplazamos los antiguos valores por los que corresponderian 
gsai2['Fatal'] = gsai2['Fatal'].replace({'N ': 'N', ' N': 'N', 'n':'N', '#VALUE!': 'UNKNOWN', 'F':'Y'})

In [207]:
#ahora tenemos solo los tres valores que queriamos para nuestra columna
gsai2['Fatal'].value_counts()

N          4325
Y          1553
UNKNOWN     114
Name: Fatal, dtype: int64

##COLUMNA SEX##

In [208]:
#vemos cuantos valores son nulos
gsai2['Sex'].isnull().sum()

567

In [209]:
#no queremos que los valores sean nulos por lo que os sustituimos por '-'
gsai2['Sex'] = gsai2['Sex'].fillna('-')

In [210]:
gsai2['Sex'].isnull().sum()

0

In [211]:
#localizamoso los valores '-'
gsai2.loc[gsai2['Sex']=='-'].head(10)

,Case Number,Date,Year,Type,Country,Area,Name,Sex,Injury,Fatal,Original Order
5977,ND.0015,Before 1917,0,Unprovoked,FIJI,Moala Island,20 Fijians,-,"FATAL, 18 people were killed by sharks, 2 sur...",Y,16
5968,ND.0024,Between 1918 & 1939,0,Unprovoked,REUNION,Saint-Denis,NaN,-,FATAL,Y,25
5949,ND.0044,1941-1945,0,Sea Disaster,NaN,NaN,C.,-,"FATAL, shark leapt into raft and bit the man w...",Y,44
5927,ND.0073,"No date, Before 1963",0,Unprovoked,SINGAPORE,NaN,NaN,-,Recovered,N,66
5909,ND.0095,Before Feb-1998,0,Unprovoked,SOLOMON ISLANDS,Malaita Province,Albert Raiti,-,Lacerations to hands and knee,N,84
5902,ND-0107,Before 2004,0,Boat,MOZAMBIQUE,Inhambane Province,"4.8-metre skiboat, Occupants: Rod Salm & 4 fri...",-,"No injury to occupants, shark bumped boat",N,91
5892,ND-0119,Before 1963,0,Unprovoked,DJIBOUTI,Gulf of Tadjoura,Passenger & crew,-,FATAL,Y,101
5887,ND-0129,Before 2012,0,Unprovoked,SPAIN,Canary Islands,NaN,-,Injury required 16 stitches,N,106
5875,ND-0150,Before 1934,0,Unprovoked,URUGUAY,Rocha,NaN,-,Foot bitten,N,118
5871,0.0725,Ca. 725 B.C.,0,Sea Disaster,ITALY,Tyrrhenian Sea,NaN,-,"Vase depicts shipwrecked sailors, one of whom ...",N,122

In [212]:
gsai1['Sex '].value_counts()

M      4835
F       585
M         2
N         1
.         1
lli       1
Name: Sex , dtype: int64

In [213]:
#miramos los vaores de 'Sex' y unificamos 
keysSex = dict(gsai2['Sex'].value_counts()).keys()

In [214]:
def cambioSexKey(x):
    for key in x:
        if key != 'M' and key != 'F' and key!='-':
            if key == 'M ' or key == 'N':
                gsai2['Sex']=gsai2['Sex'].replace({key:'M'})
            else: 
                gsai2['Sex']=gsai2['Sex'].replace({key:'-'})
cambioSexKey(keysSex)
gsai2['Sex'].value_counts()

M    4838
F     585
-     569
Name: Sex, dtype: int64

###RESULTADOS###

In [215]:
#localizamos los valores 'M'
gsai2_males = gsai2.loc[gsai2['Sex']=='M']
gsai2_males.head(30)

,Case Number,Date,Year,Type,Country,Area,Name,Sex,Injury,Fatal,Original Order
5991,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,male,M,"FATAL. ""Shark bit him in half, carrying away t...",Y,2
5990,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,Jules Patterson,M,FATAL,Y,3
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Coast Guard personnel,M,FATAL,Y,4
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Ahmun,M,FATAL,Y,5
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,male,M,FATAL,Y,6
5986,ND.0006,Before 1906,0,Unprovoked,AUSTRALIA,New South Wales,Arab boy,M,FATAL,Y,7
5985,ND.0007,Before 1906,0,Unprovoked,AUSTRALIA,NaN,fisherman,M,FATAL,Y,8
5984,ND.0008,Before 1906,0,Unprovoked,AUSTRALIA,NaN,fisherman,M,FATAL,Y,9
5983,ND.0009,Before 1906,0,Unprovoked,AUSTRALIA,NaN,boy,M,"FATAL, knocked overboard by tail of shark & ca...",Y,10
5981,ND.0011,Before 1911,0,Unprovoked,ASIA?,NaN,Mr. Masury,M,Foot severed,N,12
5980,ND.0012,Before 19-Jul-1913,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,a young Scotsman,M,"FATAL, leg stripped of flesh",Y,13
5979,ND.0013,No date (3 days after preceding incident) & pr...,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,a native fisherman,M,"FATAL, body not recovered but shark was caught...",Y,14
5978,ND.0014,Before 17-Jul-1916,0,Unprovoked,USA,North Carolina,"""youthful male""",M,"""Lost leg""",N,15
5976,ND.0016,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,male,M,FATAL,Y,17
5975,ND.0017,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,male,M,FATAL,Y,18
5974,ND.0018,Before 1911,0,Unprovoked,VIETNAM,Ba Ria-Vung Tau Province,crewman,M,Foot bitten,N,19
5973,ND.0019,Before 1921,0,Unprovoked,USA,Florida,James Kelley,M,2-inch lacerations,N,20
5972,ND.0020,1920 -1923,0,Unprovoked,AUSTRALIA,Queensland,3 Japanese divers,M,FATAL,Y,21
5971,ND.0021,No date,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Indian boy,M,"FATAL, leg severed",Y,22
5970,ND.0022,No date,0,Unprovoked,AUSTRALIA,NaN,Jaringoorli,M,Lacerations to thigh,N,23
5967,ND.0025,Before 1927,0,Unprovoked,AUSTRALIA,New South Wales,"male, the Sergeant of Marines",M,NaN,UNKNOWN,26
5966,ND.0026,Early 1930s,0,Unprovoked,BELIZE,NaN,a servant,M,FATAL,Y,27
5965,ND.0027,No date,0,Unprovoked,GREECE,Dodecanese Islands,Psarofa-gomenes,M,Head bitten,N,28
5964,ND.0028,A few years before 1938,0,Boat,ITALY,Adriatic Sea,Occupant: Mr. Maciotta,M,No injury to occupant; shark capsized boat,N,29
5963,ND.0030,Before 1905,0,Unprovoked,BURMA,NaN,male,M,Fatal x 2,Y,30
5962,ND.0031,World War II,0,Sea Disaster,PAPUA NEW GUINEA,Madang Province,male,M,Shark bumped him,N,31
5961,ND.0032,World War II,0,Sea Disaster,PAPUA NEW GUINEA,Between New Ireland & New Britain,pilot,M,"No injury, but shark removed the heel & part o...",N,32
5960,ND.0033,Before 1905,0,Provoked,BURMA,NaN,boy,M,4 finger severed by 'dead' shark. PROVOKED ACC...,N,33
5959,ND.0034,1940-1946,0,Sea Disaster,PACIFIC OCEAN,NaN,"8 US airmen in the water, 1 was bitten by a shark",M,FATAL,Y,34
5958,ND.0035,1940 - 1950,0,Unprovoked,SAUDI ARABIA,Eastern Province,a pearl diver,M,"Foot lacerated, surgically amputated",N,35

In [216]:
#localizamos de los casos en hombres los ataques con muertes y los que han sobrevivido
gsai2_m_fatal = gsai2_males.loc[gsai2_males['Fatal']=='Y']
gsai2_m_notFatal = gsai2_males.loc[gsai2_males['Fatal']=='N']
gsai2_fem = gsai2.loc[gsai2['Sex']=='F']

In [217]:
#vemos todos los casos, los casos de hombres y los casos de mujeres
print('Total cases --> ', gsai2.shape[0])
print('Females--> ', gsai2_fem.shape[0])
print('Males--> ', gsai2_males.shape[0])
#hay más casos en hombres y más en los que se sobrevive que en los que se muere
print('Males fatal--> ', gsai2_m_fatal.shape[0])
print('Males survive--> ', gsai2_m_notFatal.shape[0])

Total cases -->  5992
Females-->  585
Males-->  4838
Males fatal-->  1285
Males survive-->  3492

In [218]:
nullvals = gsai2.isnull().sum()[gsai2.isnull().sum() > 0]
nullvals

Country     43
Area       402
Name       200
Injury      27
dtype: int64

In [219]:
pd.crosstab(gsai2['Fatal'],gsai2['Sex'])

Sex        -    F     M
Fatal
N        377  456  3492
UNKNOWN   47    6    61
Y        145  123  1285

Con estos datos podemos ver que a mayor parte de los ataques no acaban en muerte

In [ ]:
gsai3 = gsai2